contact/urls.py
from django.urls import path
from contact.views import showPage

app_name = 'contact'

urlpatterns = [
    path('', showPage, name='new'),
]

eventif/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import home, speaker_detail

urlpatterns = [
    path('', home, name='home'),
    path('inscricao/', include('subscriptions.urls')),
    path('contato/', include('contact.urls')),
    path('palestrantes/<slug:slug>/', speaker_detail, name='speaker_detail'),
    path('admin/', admin.site.urls),
]

subscriptions/urls.py
from django.urls import path
from subscriptions.views import subscribe, detail

app_name = 'subscriptions'

urlpatterns = [
    path('', subscribe, name='new'),
    path('<int:pk>/', detail, name='detail'),

]

contact/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField('nome', max_length=100)
    email = models.EmailField('e-mail')
    phone = models.CharField('telefone', max_length=20, blank=True)
    message = models.TextField('mensagem', max_length=600)
    created_at = models.DateTimeField('criado em', auto_now_add=True)
    reply = models.TextField('resposta', max_length=600, blank=True)
    replied_at = models.DateTimeField('respondido em', blank=True, null=True)
    is_replied = models.BooleanField('respondido', default=False)

    class Meta:
        verbose_name_plural = 'contatos'
        verbose_name = 'contato'
        ordering = ('-created_at',)

    def __str__(self):
        return self.name

core/models.py
from django.db import models
from django.shortcuts import resolve_url as r

class Speaker(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField('slug')
    photo = models.URLField('photo')
    website = models.URLField('website', blank=True)
    description = models.TextField('description', blank=True)

    class Meta:
        verbose_name = 'palestrante'
        verbose_name_plural = 'palestrantes'
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return r('speaker_detail', slug=self.slug)

subscriptions/models.py
from django.db import models


class Subscription(models.Model):
    name = models.CharField('nome', max_length=100)
    cpf = models.CharField('CPF', max_length=11)
    email = models.EmailField('e-mail')
    phone = models.CharField('telefone', max_length=20)
    created_at = models.DateTimeField('criado em', auto_now_add=True)
    paid = models.BooleanField('pago', default=False)

    class Meta:
        verbose_name_plural = 'inscrições'
        verbose_name = 'inscrição'
        ordering = ('-created_at',)

    def __str__(self):
        return self.name

contact/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(label="Nome")
    email = forms.EmailField(label="E-Mail")
    phone = forms.CharField(label="Telefone", required=False)
    message = forms.CharField(label="Mensagem", widget=forms.Textarea)

subscriptions/forms.py
from django import forms

class SubscriptionForm(forms.Form):
    name = forms.CharField(label="Nome")
    cpf = forms.CharField(label="CPF")
    email = forms.EmailField(label="E-Mail")
    phone = forms.CharField(label="Telefone")

contact/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from contact.forms import ContactForm
from contact.models import Contact
from django.template.loader import render_to_string
from django.core import mail
from django.conf import settings

def showPage(request):
    if request.method == 'POST':
        return create(request)
    else:
        return new(request)

def create(request):
    form = ContactForm(request.POST)

    if not form.is_valid():
        return render(request, 'contact/contact_form.html', {'form': form})
    
    Contact.objects.create(**form.cleaned_data)

    _send_mail(
        'contact/contact_email.txt',
        form.cleaned_data,
        'Mensagem enviada!',
        form.cleaned_data['email'],
        settings.DEFAULT_FROM_EMAIL)

    return HttpResponseRedirect('/contato/')

def new(request):
    return render(request, 'contact/contact_form.html', {'form': ContactForm()})

def _send_mail(template_name, context, subject, from_, to):
    body = render_to_string(template_name, context)
    email = mail.send_mail(subject, body, from_, [from_, to])

core/views.py
from django.shortcuts import render, get_object_or_404
from core.models import Speaker

# Create your views here.

def home(request):
    speakers = Speaker.objects.all()
    return render(request, 'index.html', {'speakers': speakers})
def speaker_detail(request, slug):
    speaker = get_object_or_404(Speaker, slug=slug)
    return render(request, 'core/speaker_detail.html', {'speaker': speaker})

subscriptions/views.py
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, resolve_url as r
from subscriptions.forms import SubscriptionForm
from subscriptions.models import Subscription
from django.core import mail
from django.template.loader import render_to_string
from django.contrib import messages
from django.conf import settings


def subscribe(request):
    if request.method == 'POST':
        return create(request)
    else:
        return new(request)


def create(request):
    form = SubscriptionForm(request.POST)

    if not form.is_valid():
        return render(request, 'subscriptions/subscription_form.html', {'form': form})

    subscription = Subscription.objects.create(**form.cleaned_data)

    _send_mail(
        'subscriptions/subscription_email.txt',
        {'subscription': subscription},
        'Confirmação de inscrição!',
        settings.DEFAULT_FROM_EMAIL,
        subscription.email)

    return HttpResponseRedirect(r('subscriptions:detail', subscription.pk))


def new(request):
    return render(request, 'subscriptions/subscription_form.html', {'form': SubscriptionForm()})

def detail(request, pk):
    try:
        subscription = Subscription.objects.get(pk=pk)
    except Subscription.DoesNotExist:
        raise Http404

    return render(request, 'subscriptions/subscription_detail.html', {'subscription': subscription})

def _send_mail(template_name, context, subject, from_, to):
    body = render_to_string(template_name, context)
    email = mail.send_mail(subject, body, from_, [from_, to])

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>{% block title %}EventIF - O maior encontro dos IFs do mundo!{% endblock title %}</title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="description" content="EventIF - O maior encontro dos IFs do mundo!">
    <meta name="author" content="cleber">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/basalstyle/style.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <link href='http://fonts.googleapis.com/css?family=Economica:400,700' rel='stylesheet' type='text/css'>
</head>

<body>
    <div class="header-frame row">
        {% include 'nav.html' only %}
    </div>

    {% block content %}

    {% endblock content %}
</body>

</html>

templates/contact/contact_form.html
{% extends 'base.html' %}
{% block content %}
        <section>
        	<div class="content row padding-bottom-3 desktop-12 container">
                <h1>Entre em Contato</h1>
                <div class="desktop-6">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert success">
                                <p>{{ message }}</p>
                            </div>
                        {% endfor %}
                    {% endif %}
                    <form action="." novalidate method="post">
                        {% csrf_token %}
                        <div class="form-row label-block input-text">
                            <label for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
                            {{ form.name.errors }}
                            {{ form.name }}
                        </div>
                        <div class="form-row label-block input-text">
                            <label for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
                            {{ form.email.errors }}
                            {{ form.email }}
                        </div>
                        <div class="form-row label-block input-text">
                            <label for="{{ form.phone.id_for_label }}">{{ form.phone.label }}</label>
                            {{ form.phone.errors }}
                            {{ form.phone }}
                        </div>
                        <div class="form-row label-block input-text">
                            <label for="{{ form.message.id_for_label }}">{{ form.message.label }}</label>
                            {{ form.message.errors }}
                            {{ form.message }}
                        </div>
                        <p class="btn-row"><input type="submit" value="Enviar!"/></p>
                    </form>
                </div>
            </div>
        </section>
{% endblock content %}

templates/core/speaker_detail.html
{% extends 'base.html' %}

{% block content %}
<section>
    <div class="speakers content row padding-bottom-3 desktop-8 container">
        <h2>
            <a href="{{ speaker.website }}">{{ speaker.name }}</a>
        </h2>
        <img class="photo" src="{{ speaker.photo }}">
        <p>
            {{ speaker.description|linebreaks }}
        </p>
    </div>
</section>
{% endblock content %}

templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
        <title>EventIF - O maior encontro dos IFs do mundo!</title>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="description" content="EventIF - O maior encontro dos IFS do mundo!">
        <meta name="author" content="cleber">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

        <!-- Favicon -->
        <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">

        <!-- CSS -->
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/basalstyle/style.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">

        <link href='http://fonts.googleapis.com/css?family=Economica:400,700' rel='stylesheet' type='text/css'>

        <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>


        <script src="{% static 'js/jquery-1.11.0.min.js' %}"></script>
        <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
        <script src="{% static 'js/smooth-scroll.js' %}"></script>
        <script src="{% static 'js/retina-1.1.0.min.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>


	</head>

	<body>

        <div class="header-frame header-frame-absolute  row">
            {% include 'nav.html' only %}
        </div>

      	<!-- TOP -->
        <section id="top" data-stellar-background-ratio="0.5">
        	<div class="countdown text-align-center row desktop-12 container">
            	<h1 class="uppercase">EventIF</h1>
                <h3>Brasil</h3>
            </div>
        </section>

        <!-- OVERVIEW -->
        <section id="overview">
        	<div class="overview text-align-center row desktop-12 min-h-15 padding-top-2 container">
            	<i class="fa fa-5x fa-globe"></i>
            	<h2>A Conferência</h2>
                <p class="lead">A maior reunião de hackers do mundo.<br>Reunindo profissionais e entusiastas dos quatro <br>cantos do planeta, o <em>EventIF</em> é o lugar onde você precisa estar.</p>
            	<p><a class="btn-basic btn-green" data-scroll href="#register">Garanta a sua vaga!</a></p>
            </div>
        </section>

        <section id="speakers">
            <div class="speakers text-align-center row desktop-8 padding-bottom-2 container">
                <h2>Palestrantes Convidados</h2>
                {% for speaker in speakers %}
                <div class="desktop-4">
                    <img src="{{ speaker.photo }}">
                    <h4><a href="{{ speaker.get_absolute_url }}">
                        {{ speaker.name }}
                    </a>
                </h4>
                </div>
                {% endfor %}  
            </div>
        </section>

        <!-- SPONSORS -->
        <section id="sponsors">
        	<div class="sponsors text-align-center row desktop-12 min-h-28 padding-bottom-2 container">

                <h2>Patrocinadores</h2>

                <h3>Gold</h3>
                <div class="sponsor-slider min-h-6">
                    <img class="img-responsive" src="{% static 'img/sponsor-gold-01.png' %}" alt="logo">
                    <img class="img-responsive" src="{% static 'img/sponsor-gold-02.png' %}" alt="logo">
                    <img class="img-responsive" src="{% static 'img/sponsor-gold-03.png' %}" alt="logo">

                </div>

                <h3>Silver</h3>
                <div class="sponsor-slider min-h-6 margin-bottom-1">
                	<img class="img-responsive" src="{% static 'img/sponsor-silver-01.png' %}" alt="logo">
                    <img class="img-responsive" src="{% static 'img/sponsor-silver-02.png' %}" alt="logo">
                    <img class="img-responsive" src="{% static 'img/sponsor-silver-03.png' %}" alt="logo">
                    <img class="img-responsive" src="{% static 'img/sponsor-silver-04.png' %}" alt="logo">
                    <img class="img-responsive" src="{% static 'img/sponsor-silver-05.png' %}" alt="logo">
                    <img class="img-responsive" src="{% static 'img/sponsor-silver-06.png' %}" alt="logo">
                </div>

                <h3>Seja um patrocinador</h3>
                <p>Interessado? Descubra as oportunidades e benefícios.</p>
                <a class="btn-basic btn-green" href="mailto:contato@eventif.com.br?Subject=Patrocínio">informe-se</a>

            </div>
        </section>

        <!-- REGISTER -->
        <section id="register">
            <div class="register row">
                <div class="text-align-center row desktop-12 padding-top-2 min-h-14 container">
                	<h2>Inscrição</h2>
                	<h3>Inscrições abertas!</h3>
                	<a class="btn-basic btn-green" href="{% url 'subscriptions:new' %}">Inscreva-se Já!</a>
                </div>
            </div>
        </section>

        <!-- VENUE -->
        <section id="venue">
            <div class="row min-h-10">

                <div id="map-canvas"></div>
                <div class="row desktop-12 container">
                    <div class="venue row">
                        <div class="venue-address desktop-4 gutter">
                            <h2>IFRS - Campus Rio Grande</h2>
                            <p>Anfiteatro.</p>
                            <p class="address">
                                <i class="fa fa-2x fa-map-marker fa-inverse"></i>
                                Rua Engenheiro Alfredo Huch, 475, Centro<br>
                                Rio Grande, RS
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </body>
</html>

templates/nav.html
{% load static %}
<header class="header header-inline min-h-3 row desktop-12 container" role="banner">

    <div class="site-logo">
        <h1><a href="{% url 'home' %}" rel="home">EventIF</a></h1>
        <p class="site-description screen-reader-only">O maior encontro dos IFs do mundo!</p>
    </div>

    <nav class="nav-inline" role="navigation">
        <a href="javascript:void(0);" class="nav-mobile"><i class="fa fa-bars"></i></a>
        <ul>
            <li><a data-scroll href="{% url 'home' %}#overview">Conferência</a></li>
            <li><a data-scroll href="{% url 'home' %}#speakers">Palestrantes</a></li>
            <li><a data-scroll href="{% url 'home' %}#sponsors">Patrocinadores</a></li>
            <li><a data-scroll href="{% url 'home' %}#register">Inscrição</a></li>
            <li><a data-scroll href="/contato/">Contato</a></li>
            <li><a data-scroll href="{% url 'home' %}#venue">Local</a></li>
        </ul>
    </nav>

</header>

templates/subscriptions/subscription_detail.html
{% extends 'base.html' %}
{% block content %}
<!-- OVERVIEW -->
<section>
    <div class="content row padding-bottom-3 desktop-12 container">
        <h1>Obrigado por se inscrever no Eventif!</h1>
        <div class="desktop-6">
            <p>Estes foram os dados que você enviou na sua inscrição.</p>
            
            <ul>
                <li>Nome: {{subscription.name}}</li>
                <li>CPF: {{subscription.cpf}}</li>
                <li>Email: {{subscription.email}}</li>
                <li>Telefone: {{subscription.phone}}</li>
            </ul>
            
            <p>Em até 48h úteis alguem da nossa equipe entrará em contato com você para concluirmos a sua inscrição.</p>
        </div>
    </div>
</section>
{% endblock content %}

templates/subscriptions/subscription_form.html
{% extends 'base.html' %}
{% block content %}
<!-- OVERVIEW -->
<section>
    <div class="content row padding-bottom-3 desktop-12 container">
        <h1>Formulário de Inscrição</h1>
        <div class="desktop-6">
            {% if messages %}
            {% for message in messages %}
            <div class="alert success">
                <p>{{ message }}</p>
            </div>
            {% endfor %}
            {% endif %}
            <form action="." novalidate method="post">
                {% csrf_token %}
                <div class="form-row label-block input-text">
                    <label for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
                    {{ form.name.errors }}
                    {{ form.name }}
                </div>
                <div class="form-row label-block input-text">
                    <label for="{{ form.cpf.id_for_label }}">{{ form.cpf.label }}</label>
                    {{ form.cpf.errors }}
                    {{ form.cpf }}
                </div>
                <div class="form-row label-block input-text">
                    <label for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
                    {{ form.email.errors }}
                    {{ form.email }}
                </div>
                <div class="form-row label-block input-text">
                    <label for="{{ form.phone.id_for_label }}">{{ form.phone.label }}</label>
                    {{ form.phone.errors }}
                    {{ form.phone }}
                </div>
                <p class="btn-row"><input type="submit" value="Enviar!" /></p>
            </form>
        </div>
    </div>
</section>
{% endblock content%}